In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics as st
import datetime as dt
import seaborn as sns

In [4]:
# IMPORTING THE DATSET
data = pd.read_csv(r'D:\Nike_Sales_Uncleaned.csv')

In [3]:
backup_data = pd.read_csv("Nike_Sales_Uncleaned.csv")

In [6]:
data

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,NaN,0.0,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,L,-1.0,NaN,NaN,0.0,NaN,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.0,02-07-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,NaN,4.0,5358.70,NaN,0.0,11-12-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,NaN,0.0,23-11-2024,Retail,Mumbai,2453.57

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              1990 non-null   object
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(1), object(7)
memory usage: 254.0+ KB

In [6]:
data.describe()

,Order_ID,Units_Sold,MRP,Discount_Applied,Revenue,Profit
count,2500.000000,1265.000000,1246.000000,832.000000,2500.000000,2500.000000
mean,3194.352400,1.482213,6039.863395,0.631022,274.873716,1376.012848
std,749.972638,1.696947,2315.746826,0.365500,2023.773550,1478.671013
min,2000.000000,-1.000000,2006.630000,0.000000,-7561.590000,-1199.450000
25%,2534.750000,0.000000,4038.902500,0.320000,0.000000,93.532500
50%,3192.500000,2.000000,6110.030000,0.615000,0.000000,1371.385000
75%,3841.250000,3.000000,8022.187500,0.962500,0.000000,2660.645000
max,4499.000000,4.000000,9996.220000,1.250000,37169.350000,3999.210000

## CLEANING AND PREPROCESSING

### CLEANING AND PREPROCESSING THE SIZE COLUMN

In [7]:
# DISPLAYS UNIQUE VALUES AND THEIR COUNT TO KNOW ABOUT DIVERSITY AND ENTRIES IN THE SIZE COLUMN

data['Size'].value_counts()

Size
L     513
XL    512
M     478
7      86
11     77
10     76
9      68
12     61
8      60
6      59
Name: count, dtype: int64

In [8]:
data[data['Size'].isin(['M',"L","XL"])]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,M,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,M,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,M,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,L,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,XL,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2493,4493,Women,Lifestyle,Blazer Mid,XL,4.0,NaN,NaN,0.0,2024-10-04,Online,Mumbai,321.24
2494,4494,Women,Training,ZoomX Invincible,L,NaN,NaN,NaN,0.0,12-02-2025,Online,Kolkata,1357.29
2495,4495,Kids,Basketball,Kyrie Flytrap,XL,3.0,NaN,NaN,0.0,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,L,-1.0,NaN,NaN,0.0,NaN,Online,Hyd,-487.36
2499,4499,Women,Running,Air Zoom,M,NaN,5550.99,NaN,0.0,23-11-2024,Retail,Mumbai,2453.57

In [10]:
# REPLACING THE SIZES FIRSTLY IN STRING TO MATCH THE PRESET DATATYPE AND THEN WE'LL CONVERT IT INTO THE INT64

data['Size'].replace("M","8",inplace=True)
data['Size'].replace("L","10",inplace=True)
data['Size'].replace("XL","12",inplace=True)

C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\3619721453.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Size'].replace("M","8",inplace=True)
C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\3619721453.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Size'].replace("L","10",inplace=True)
C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\3619721453.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Size'].replace("XL","12",inplace=True)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THE ALPHABETICAL SIZES ARE CONVERTED INTO NUMERICAL ONES BASED ON AVG. SUBSTITUION FROM THE INFO AVAILABLE ON GOOGLE.
M->8
L->10
XL->12

In [11]:
data["Size"].value_counts()

Size
10    589
12    573
8     538
7      86
11     77
9      68
6      59
Name: count, dtype: int64

In [ ]:
# ONE OF THE TWO ENTRIES IN THE SIZE COLUMN IS A STRING AND THE OTHER IS AN INT64, SO WE'LL CONVERT THE DATATYPE OF THE SIZE COLUMN FROM OBJECT TO INT64

data[data['Size']=="8"].count()

Order_ID            538
Gender_Category     538
Product_Line        538
Product_Name        538
Size                538
Units_Sold          272
MRP                 257
Discount_Applied    170
Revenue             538
Order_Date          391
Sales_Channel       538
Region              538
Profit              538
dtype: int64

In [ ]:
# CHANGING THE DATATYPE OF THE SIZE COLUMN FROM OBJECT TO INT64

data['Size'] = data['Size'].astype(np.int64,errors='ignore')

In [14]:
# THE DATA SHOWS INT64 BUT HAS STRING BECAUSE TILL NOW IT CONTAINS NaN

data[data['Size']=="10"].count()

Order_ID            589
Gender_Category     589
Product_Line        589
Product_Name        589
Size                589
Units_Sold          298
MRP                 304
Discount_Applied    201
Revenue             589
Order_Date          458
Sales_Channel       589
Region              589
Profit              589
dtype: int64

In [15]:
data.isnull().sum()

Order_ID               0
Gender_Category        0
Product_Line           0
Product_Name           0
Size                 510
Units_Sold          1235
MRP                 1254
Discount_Applied    1668
Revenue                0
Order_Date           616
Sales_Channel          0
Region                 0
Profit                 0
dtype: int64

In [16]:
data[['Gender_Category','Product_Line',"Size"]]

     Gender_Category Product_Line Size
0               Kids     Training    8
1              Women       Soccer    8
2              Women       Soccer    8
3               Kids    Lifestyle   10
4               Kids      Running   12
...              ...          ...  ...
2495            Kids   Basketball   12
2496             Men   Basketball   10
2497             Men       Soccer    7
2498           Women     Training  NaN
2499           Women      Running    8

[2500 rows x 3 columns]

In [17]:
# HERE IT IS CHECKED THAT WHETHER WE HAVE THE SUFFICIENT VALUES TO COMPUTE THE MEAN/MEDIAN TO SUBSTITE AND FILL THE NULL VALUES.

data.groupby(['Gender_Category','Product_Line'],as_index=True).count()

                              Order_ID  Product_Name  Size  Units_Sold  MRP  \
Gender_Category Product_Line
Kids            Basketball         172           172   135          82   88
                Lifestyle          173           173   142          95   84
                Running            163           163   128          71   94
                Soccer             148           148   118          80   69
                Training           185           185   144          93   92
Men             Basketball         174           174   138          81   90
                Lifestyle          161           161   132          80   88
                Running            146           146   113          72   68
                Soccer             172           172   136          94   82
                Training           187           187   150         100   83
Women           Basketball         161           161   131          80   85
                Lifestyle          167           167   134          82   91
                Running            165           165   134          84   79
                Soccer             152           152   118          83   67
                Training           174           174   137          88   86

                              Discount_Applied  Revenue  Order_Date  \
Gender_Category Product_Line
Kids            Basketball                  66      172         140
                Lifestyle                   54      173         134
                Running                     54      163         114
                Soccer                      38      148         113
                Training                    57      185         136
Men             Basketball                  56      174         139
                Lifestyle                   56      161         119
                Running                     50      146         109
                Soccer                      60      172         125
                Training                    66      187         134
Women           Basketball                  56      161         117
                Lifestyle                   47      167         135
                Running                     52      165         118
                Soccer                      58      152         124
                Training                    62      174         127

                              Sales_Channel  Region  Profit
Gender_Category Product_Line
Kids            Basketball              172     172     172
                Lifestyle               173     173     173
                Running                 163     163     163
                Soccer                  148     148     148
                Training                185     185     185
Men             Basketball              174     174     174
                Lifestyle               161     161     161
                Running                 146     146     146
                Soccer                  172     172     172
                Training                187     187     187
Women           Basketball              161     161     161
                Lifestyle               167     167     167
                Running                 165     165     165
                Soccer                  152     152     152
                Training                174     174     174

In [18]:
# HERE CATEGORY AND GROUP-WISE UNIQUE VALUES ARE CHECKED TO IDENTIFY THE PATTERN AND DIVERSITY OR ROBUSTNESS OF OUTLIERS.

data.groupby(['Gender_Category','Product_Line'])['Size'].unique()

Gender_Category  Product_Line
Kids             Basketball      [nan, 10, 12, 8, 11, 9, 7, 6]
                 Lifestyle       [10, nan, 12, 8, 9, 7, 11, 6]
                 Running         [12, 6, 7, nan, 10, 11, 8, 9]
                 Soccer          [10, 12, nan, 8, 6, 9, 11, 7]
                 Training        [8, nan, 12, 10, 9, 11, 6, 7]
Men              Basketball      [12, 6, 10, nan, 9, 8, 7, 11]
                 Lifestyle       [8, 12, 10, nan, 6, 7, 9, 11]
                 Running         [10, nan, 12, 11, 7, 8, 6, 9]
                 Soccer          [8, 12, nan, 10, 11, 7, 9, 6]
                 Training        [8, 12, nan, 10, 7, 11, 6, 9]
Women            Basketball      [8, 9, 12, 10, nan, 7, 11, 6]
                 Lifestyle       [12, 10, nan, 8, 6, 11, 7, 9]
                 Running         [11, 12, nan, 8, 9, 10, 7, 6]
                 Soccer          [8, 11, 12, 10, 7, nan, 9, 6]
                 Training        [8, 10, 11, nan, 12, 6, 7, 9]
Name: Size, dtype: object

In [19]:
# THE SIZE COLUMN IS FORCED TO NUMERIC FORMAT AND THEN THE NULL VALUES ARE FILLED WITH THE MEDIAN OF GROUP-WISE AVAILABLE VALUES TO SUPPORT THE SUBSTITUTION.

data['Size'] = pd.to_numeric(data['Size'],errors='coerce')
data['Size'] = data.groupby(['Gender_Category','Product_Line'])['Size'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
# CONVERTING THE DATATYPE OF THE SIZE COLUMN FROM OBJECT TO INT64

data['Size'] = data['Size'].astype(np.int64)

In [21]:
data['Size'].isnull().sum()

np.int64(0)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              2500 non-null   int64
 5   Units_Sold        1265 non-null   float64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 254.0+ KB

-> THE SIZE COLUMN HAD MIXED ENTRIES IN SIZE COLUMN, FOR THAT THE ALPHABETICAL VALUES WERE CONVERTED INTO NUMERICAL VALUES.

-> THE VALUES WERE FIRSTLY REPLACED WITH STRING DATATYPE TO MATCH THE SIMILAR NUMERCIAL COUNTS AUTOMATICALLY AND THEN IT WAS CONVERTED INTO THE "INT64".

-> THE NULL VALUES WERE REPLACED WITH THE MEDIAN OF THE GROUP-WISE INFORMATION AND VALUES AVAILABLE USING GROUPYBY AND TRANSFORM FUNCTIONS.

### CLEANING AND PREPROCESSING THE UNITS_SOLD COLUMN

In [23]:
# THE UNIT SOLD COLUMN OTHER THAN THE NULL VALUES ALSO HAD THE 0.0 VALUES

data[data['Units_Sold']==0]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
18,2018,Men,Training,Metcon 7,12,0.0,NaN,1.17,0.0,NaN,Online,bengaluru,-966.89
19,2019,Kids,Running,Air Zoom,6,0.0,3424.06,0.32,0.0,2025/01/17,Online,Hyderabad,1915.24
24,2024,Kids,Training,SuperRep Go,12,0.0,NaN,0.50,0.0,28-12-2024,Retail,Bangalore,1842.35
29,2029,Men,Training,ZoomX Invincible,12,0.0,NaN,NaN,0.0,2023-10-28,Online,Bangalore,-185.67
38,2038,Kids,Running,Free RN,9,0.0,NaN,0.83,0.0,NaN,Online,Delhi,1163.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2447,4447,Kids,Running,Free RN,12,0.0,NaN,NaN,0.0,2024-12-12,Retail,Delhi,1574.91
2449,4449,Men,Lifestyle,Air Force 1,9,0.0,5053.29,NaN,0.0,2025/02/24,Retail,Kolkata,3206.34
2451,4451,Women,Lifestyle,Dunk Low,9,0.0,2049.73,NaN,0.0,08-11-2024,Online,Pune,2543.16
2490,4490,Women,Training,Metcon 7,10,0.0,NaN,NaN,0.0,23-02-2025,Online,Kolkata,-1173.84
2491,4491,Women,Running,Pegasus Turbo,8,0.0,NaN,NaN,0.0,NaN,Online,Kolkata,3066.85

In [24]:
data['Units_Sold'].value_counts()

Units_Sold
 2.0    234
 0.0    224
 4.0    212
-1.0    205
 1.0    203
 3.0    187
Name: count, dtype: int64

In [25]:
# REPLACING THE -VE VALUES WITH +VE ONES

data['Units_Sold'].replace(-1.0,1.0,inplace=True)

C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\4220573512.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Units_Sold'].replace(-1.0,1.0,inplace=True)

In [26]:
data

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
0,2000,Kids,Training,SuperRep Go,8,NaN,NaN,0.47,0.0,2024-03-09,Online,bengaluru,-770.45
1,2001,Women,Soccer,Tiempo Legend,8,3.0,4957.93,NaN,0.0,2024-07-09,Retail,Hyd,-112.53
2,2002,Women,Soccer,Premier III,8,4.0,NaN,NaN,0.0,NaN,Retail,Mumbai,3337.34
3,2003,Kids,Lifestyle,Blazer Mid,10,NaN,9673.57,NaN,0.0,04-10-2024,Online,Pune,3376.85
4,2004,Kids,Running,React Infinity,12,NaN,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,12,3.0,NaN,NaN,0.0,2025-05-14,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,10,1.0,NaN,NaN,0.0,NaN,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,NaN,6647.60,0.52,0.0,02-07-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,9,4.0,5358.70,NaN,0.0,11-12-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,8,NaN,5550.99,NaN,0.0,23-11-2024,Retail,Mumbai,2453.57

In [27]:
# CHECKING THE CATEGORY-WISE (GROUP-WISE) MEDIAN 

data.groupby(['Gender_Category','Product_Name'])['Units_Sold'].median()

Gender_Category  Product_Name
Kids             Air Force 1           1.0
                 Air Jordan            1.0
                 Air Zoom              1.0
                 Blazer Mid            2.0
                 Dunk Low              2.0
                 Flex Trainer          1.0
                 Free RN               1.0
                 Kyrie Flytrap         1.0
                 LeBron 20             1.0
                 Mercurial Superfly    2.0
                 Metcon 7              2.0
                 Pegasus Turbo         1.0
                 Phantom GT            2.0
                 Premier III           2.0
                 React Infinity        2.0
                 SuperRep Go           2.0
                 Tiempo Legend         2.0
                 Waffle One            2.0
                 Zoom Freak            2.0
                 ZoomX Invincible      1.0
Men              Air Force 1           2.0
                 Air Jordan            2.0
                 Air Zoom              2.0
                 Blazer Mid            1.0
                 Dunk Low              2.0
                 Flex Trainer          3.0
                 Free RN               1.0
                 Kyrie Flytrap         1.0
                 LeBron 20             2.0
                 Mercurial Superfly    1.0
                 Metcon 7              1.0
                 Pegasus Turbo         1.0
                 Phantom GT            1.0
                 Premier III           2.0
                 React Infinity        2.5
                 SuperRep Go           2.0
                 Tiempo Legend         1.0
                 Waffle One            2.0
                 Zoom Freak            2.5
                 ZoomX Invincible      1.0
Women            Air Force 1           2.0
                 Air Jordan            2.0
                 Air Zoom              1.0
                 Blazer Mid            2.0
                 Dunk Low              1.5
                 Flex Trainer          1.0
                 Free RN               2.0
                 Kyrie Flytrap         2.0
                 LeBron 20             1.0
                 Mercurial Superfly    1.0
                 Metcon 7              1.0
                 Pegasus Turbo         1.0
                 Phantom GT            1.0
                 Premier III           1.0
                 React Infinity        1.0
                 SuperRep Go           1.0
                 Tiempo Legend         2.0
                 Waffle One            2.0
                 Zoom Freak            2.0
                 ZoomX Invincible      2.0
Name: Units_Sold, dtype: float64

In [28]:
# CHECKING THE GROUP-WISE UNIQUE VALUES TO SEE OUTLIERS AND DIVERSITY AMONG THE VALUES PER EACH GROUP.

data.groupby(['Gender_Category','Product_Name'])['Units_Sold'].unique()

Gender_Category  Product_Name
Kids             Air Force 1           [nan, 0.0, 1.0, 3.0, 4.0, 2.0]
                 Air Jordan            [nan, 4.0, 1.0, 0.0, 3.0, 2.0]
                 Air Zoom              [0.0, nan, 1.0, 3.0, 4.0, 2.0]
                 Blazer Mid            [nan, 1.0, 3.0, 4.0, 2.0, 0.0]
                 Dunk Low                   [4.0, nan, 1.0, 3.0, 2.0]
                 Flex Trainer          [1.0, 4.0, 0.0, nan, 3.0, 2.0]
                 Free RN               [0.0, nan, 1.0, 2.0, 4.0, 3.0]
                 Kyrie Flytrap         [nan, 2.0, 1.0, 4.0, 3.0, 0.0]
                 LeBron 20             [4.0, 1.0, nan, 0.0, 3.0, 2.0]
                 Mercurial Superfly    [2.0, 0.0, nan, 4.0, 3.0, 1.0]
                 Metcon 7              [2.0, 4.0, nan, 1.0, 0.0, 3.0]
                 Pegasus Turbo              [3.0, 1.0, nan, 0.0, 2.0]
                 Phantom GT            [1.0, 2.0, nan, 3.0, 0.0, 4.0]
                 Premier III           [1.0, 2.0, nan, 0.0, 4.0, 3.0]
                 React Infinity        [nan, 2.0, 1.0, 0.0, 3.0, 4.0]
                 SuperRep Go           [nan, 1.0, 0.0, 4.0, 3.0, 2.0]
                 Tiempo Legend         [1.0, nan, 4.0, 3.0, 2.0, 0.0]
                 Waffle One            [1.0, 0.0, nan, 2.0, 4.0, 3.0]
                 Zoom Freak            [4.0, nan, 2.0, 0.0, 3.0, 1.0]
                 ZoomX Invincible      [1.0, 3.0, 0.0, nan, 4.0, 2.0]
Men              Air Force 1           [3.0, 0.0, 4.0, nan, 1.0, 2.0]
                 Air Jordan            [nan, 2.0, 3.0, 1.0, 4.0, 0.0]
                 Air Zoom              [1.0, nan, 4.0, 3.0, 2.0, 0.0]
                 Blazer Mid            [nan, 0.0, 1.0, 2.0, 4.0, 3.0]
                 Dunk Low              [nan, 0.0, 1.0, 4.0, 2.0, 3.0]
                 Flex Trainer          [nan, 3.0, 1.0, 2.0, 4.0, 0.0]
                 Free RN               [1.0, 4.0, nan, 0.0, 2.0, 3.0]
                 Kyrie Flytrap         [nan, 1.0, 4.0, 0.0, 2.0, 3.0]
                 LeBron 20             [nan, 2.0, 3.0, 4.0, 0.0, 1.0]
                 Mercurial Superfly    [4.0, 1.0, 0.0, nan, 3.0, 2.0]
                 Metcon 7              [0.0, 3.0, 2.0, 1.0, nan, 4.0]
                 Pegasus Turbo         [1.0, 2.0, 0.0, nan, 4.0, 3.0]
                 Phantom GT            [nan, 1.0, 0.0, 3.0, 2.0, 4.0]
                 Premier III           [4.0, nan, 3.0, 1.0, 2.0, 0.0]
                 React Infinity        [3.0, 0.0, nan, 1.0, 2.0, 4.0]
                 SuperRep Go           [nan, 3.0, 4.0, 1.0, 2.0, 0.0]
                 Tiempo Legend         [0.0, nan, 2.0, 4.0, 1.0, 3.0]
                 Waffle One            [nan, 3.0, 2.0, 1.0, 4.0, 0.0]
                 Zoom Freak            [nan, 2.0, 3.0, 0.0, 4.0, 1.0]
                 ZoomX Invincible      [0.0, nan, 2.0, 4.0, 1.0, 3.0]
Women            Air Force 1           [nan, 2.0, 1.0, 3.0, 0.0, 4.0]
                 Air Jordan                 [1.0, 4.0, nan, 3.0, 2.0]
                 Air Zoom              [nan, 1.0, 0.0, 3.0, 2.0, 4.0]
                 Blazer Mid            [1.0, 4.0, nan, 2.0, 3.0, 0.0]
                 Dunk Low                   [nan, 2.0, 4.0, 1.0, 0.0]
                 Flex Trainer          [1.0, nan, 2.0, 4.0, 0.0, 3.0]
                 Free RN               [4.0, nan, 2.0, 0.0, 3.0, 1.0]
                 Kyrie Flytrap         [3.0, nan, 1.0, 0.0, 2.0, 4.0]
                 LeBron 20             [nan, 0.0, 1.0, 2.0, 4.0, 3.0]
                 Mercurial Superfly    [1.0, 0.0, nan, 2.0, 4.0, 3.0]
                 Metcon 7              [nan, 1.0, 4.0, 2.0, 0.0, 3.0]
                 Pegasus Turbo              [nan, 0.0, 3.0, 2.0, 1.0]
                 Phantom GT            [1.0, nan, 0.0, 3.0, 4.0, 2.0]
                 Premier III           [4.0, 1.0, nan, 0.0, 3.0, 2.0]
                 React Infinity        [nan, 4.0, 1.0, 0.0, 3.0, 2.0]
                 SuperRep Go           [1.0, nan, 0.0, 4.0, 3.0, 2.0]
                 Tiempo Legend         [3.0, nan, 1.0, 2.0, 4.0, 0.0]
                 Waffle One            [nan, 4.0, 1.0, 2.0, 3.0, 0.0]
                 Zoom Freak            [3.0, nan, 0.0, 1.0, 2.0, 4.0]
                 ZoomX Invincible      [nan, 2.0, 3.0, 4.0, 1.0, 0.0]
Name: Units_Sold, dtype: object

In [29]:
# AFTER FINDING SUFFICIENT VALUES, THE 0.0 VALUES WAS SUBSTITUTED WITH GROUP-WISE MEADIAN

data['Units_Sold'] = data.groupby(['Gender_Category','Product_Name'])['Units_Sold'].transform(lambda x: x.replace(0.0,x[x!=0.0].median()))

In [30]:
# CHANGING THE THE DATA TYPE TO NUMERICAL FORMAT

data["Units_Sold"] = pd.to_numeric(data["Units_Sold"],errors='coerce',downcast='integer')

In [31]:
data["Units_Sold"].value_counts()

Units_Sold
1.0    443
2.0    359
3.0    226
4.0    212
1.5     20
2.5      5
Name: count, dtype: int64

In [32]:
# CONVERTING THE MEDIAN FLOAT VALUES TO ABSOLUTE INTEGER VALUES.

data["Units_Sold"].replace(1.5,2,inplace=True)
data["Units_Sold"].replace(2.5,3,inplace=True)

C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\3527405352.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Units_Sold"].replace(1.5,2,inplace=True)
C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\3527405352.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Units_Sold"].replace(2.5,3,inplace=True)

In [33]:
data["Units_Sold"].isnull().sum()

np.int64(1235)

In [34]:
# REPLACING THE NULL VALUES WITH THE GROUP-WISE MEDIAN BUT AFTER THE 0.0 VALUES ARE ALREADY REPLACED TO INCREASE THE ACCURACY

data['Units_Sold'] = data.groupby(['Gender_Category','Product_Name'])['Units_Sold'].transform(lambda x: x.fillna(x.median()))

In [35]:
data['Units_Sold'].isnull().sum()

np.int64(0)

In [36]:
# CHANGING DATA TYPE TO INT64

data['Units_Sold'] = data['Units_Sold'].astype(np.int64)

In [37]:
data['Units_Sold']

0       3
1       3
2       4
3       3
4       2
       ..
2495    3
2496    1
2497    1
2498    4
2499    1
Name: Units_Sold, Length: 2500, dtype: int64

In [38]:
data['Units_Sold'].value_counts()

Units_Sold
2    1186
1     604
3     498
4     212
Name: count, dtype: int64

In [39]:
data[data['Units_Sold']==2]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount_Applied,Revenue,Order_Date,Sales_Channel,Region,Profit
4,2004,Kids,Running,React Infinity,12,2,NaN,NaN,0.0,2024/09/12,Retail,Delhi,187.89
14,2014,Women,Running,React Infinity,11,2,NaN,NaN,0.0,2025-04-12,Online,Bangalore,-1044.40
18,2018,Men,Training,Metcon 7,12,2,NaN,1.17,0.0,NaN,Online,bengaluru,-966.89
19,2019,Kids,Running,Air Zoom,6,2,3424.06,0.32,0.0,2025/01/17,Online,Hyderabad,1915.24
23,2023,Men,Lifestyle,Waffle One,8,2,5003.95,NaN,0.0,10-01-2025,Online,Mumbai,1498.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488,4488,Women,Training,Flex Trainer,8,2,NaN,NaN,0.0,2024/12/16,Retail,Pune,3045.38
2490,4490,Women,Training,Metcon 7,10,2,NaN,NaN,0.0,23-02-2025,Online,Kolkata,-1173.84
2491,4491,Women,Running,Pegasus Turbo,8,2,NaN,NaN,0.0,NaN,Online,Kolkata,3066.85
2492,4492,Men,Lifestyle,Air Force 1,8,2,NaN,NaN,0.0,NaN,Retail,Mumbai,2397.23
2494,4494,Women,Training,ZoomX Invincible,10,2,NaN,NaN,0.0,12-02-2025,Online,Kolkata,1357.29

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              2500 non-null   int64
 5   Units_Sold        2500 non-null   int64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        1884 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(4), int64(3), object(6)
memory usage: 254.0+ KB

-> THE UNITS SOLD COLUMN HAD 0.0 VALUES AND NULL VALUES AS WELL.

-> THE 0.0 VALUES WERE REPLACED WITH THE MEDIAN OF THE GROUP-WISE MEDIAN BEFORE FILLING UP THE NULL VALUES, SO THAT WE HAVVE MORE CONCRETE SUPPORT FOR FILLING THE NULL VALUES.

-> AFTER FILLING THE MEDIAN, IT LED TO SOME "DECIMAL" VALUES WHICH IS NOT ACCEPTABLE FOR SOMETHING LIKE QUANTITY, HENCE THOSE VALUES WERE REPLACED TO ABSOLUTE VALUES, AND THEN TO AVOID SUCH PROBELEM IN FUTURE THE COLUMN WAS THEN CONVERTED INTO "INT64".

-> FINALLY, THE NULL VALUES WERE FILLED WITH THE GROUP-WISE MEDIAN.

### CLEANING AND PREPROCESSING THE ORDER_DATE COLUMN

In [41]:
# SORTING THE DATAFRAME W.R.T. "ORDER_DATE" BECUASE WE DECIDED TO FILL IT WITH FORWARD FILL METHOD.

data.sort_values(by='Order_Date',ascending=True,inplace=True)

In [42]:
# CHECKING NULL VALUES IN THE COLUMN

data['Order_Date'].isnull().sum()

np.int64(616)

In [43]:
# CHECKING THE DIVERSITY IN THE VALUES. (EVENTUALLY TOLD US ABOUT THE MIXED FORMAT OF THE VALUES STORED)

data['Order_Date'].value_counts()

Order_Date
10-12-2024    6
2024/11/10    6
2024/12/16    6
17-11-2024    6
19-07-2025    6
             ..
2024/08/17    1
2024/08/12    1
2024/08/11    1
2024/08/10    1
2024/08/09    1
Name: count, Length: 1008, dtype: int64

In [44]:
# USING THE FORWARD FILL METHOD TO FILL THE NULL VALUES BECAUSE IT IS NOT POSSIBLE TO FILL IT WITH ANY STATISTICAL APPROACH/MEASURE.

data['Order_Date'].fillna(method='ffill',inplace=True)

C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\2505791403.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Order_Date'].fillna(method='ffill',inplace=True)
C:\Users\Krish\AppData\Local\Temp\ipykernel_18496\2505791403.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['Order_Date'].fillna(method='ffill',inplace=True)

In [45]:
# SOME PREPROCESSING BEFORE MAKING THE VALUES INTO SAME FORMAT SO THAT LIBRARIES ARE GIVEN A SAME SORT OF INPUT AND IT CAN CONVERTED INTO DATETIME FORMAT.

data['Order_Date'].replace('/','-',inplace=True)

In [46]:
# CHANGING THE DATATYPE FROM "OBJECT" TO "DATETIME" TO USE THE FEATURES ASSOCIATED WITH IT.

data['Order_Date'] = pd.to_datetime(data['Order_Date'],errors='coerce',format='mixed')

In [47]:
# CHANGING THE FORMAT OF THE DATE TO DD/MM/YY

data['Order_Date']=data['Order_Date'].dt.strftime('%d-%m-%Y')

In [48]:
data['Order_Date']

2078    01-01-2025
1410    01-01-2025
2270    01-01-2025
99      02-01-2025
649     02-01-2025
           ...
2474    31-12-2024
2478    31-12-2024
2491    31-12-2024
2492    31-12-2024
2496    31-12-2024
Name: Order_Date, Length: 2500, dtype: object

In [49]:
# SORTED THE DATAFRAME AGAIN BASED ON ORDER_ID

data.sort_values(by='Order_ID',ascending=True,inplace=True)

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2500 entries, 211 to 2499
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2500 non-null   int64
 1   Gender_Category   2500 non-null   object
 2   Product_Line      2500 non-null   object
 3   Product_Name      2500 non-null   object
 4   Size              2500 non-null   int64
 5   Units_Sold        2500 non-null   int64
 6   MRP               1246 non-null   float64
 7   Discount_Applied  832 non-null    float64
 8   Revenue           2500 non-null   float64
 9   Order_Date        2500 non-null   object
 10  Sales_Channel     2500 non-null   object
 11  Region            2500 non-null   object
 12  Profit            2500 non-null   float64
dtypes: float64(4), int64(3), object(6)
memory usage: 273.4+ KB

-> THE ORDER DATE COLUMN HAD ISSUES WITH NULL VALUES, MIXED DATE FORMAT, AND DIFFRENT DATA TYPE.

-> THE DATAFRAME WAS FIRSTLY SORTED BASED ON THE ORDER DATE COLUMN TO USE FORWARD FILL METHOD TO FILL THE NULL VALUES, BECAUSE IT IS MATTER FOR DATE HENCE IT WAS UNMEANINGFULL TO FILL THE VALUES WITH ANY STATISTICAL MEASURE.

-> BEFORE THAT THE DATA WAS PREPARED TO BE CONVERTED INTO "DATETIME" FROM OBJECT DATATYPE TO MAKE A UNFORM DATE FORMAT ALL OVER THE COLUMN AND SO THAT THE NULL VALUES ARE FILLED CORRECTLY.

-> FINALLY THE COLUMN WAS CONVERTED INTO DATE HAVING DD/MM/YYYY FORMAT AND ALSO THE DATA FRAME WAS FINALLY SORTED AND ARRANGED INTO ASCENDING ORDER BASED ON ORDER_ID.

### CLEANING AND PREPROCESSING THE DISCOUNT COLUMN

In [51]:
# RENAMED THE DISCOUNT COLUMN TO MAKE IT EASY TO WRITE.

data.rename({'Discount_Applied':"Discount"},axis=1,inplace=True)

In [52]:
# CHECKING DIVERSITY AND TYPE OF VALUES AVAIALBLE 

data["Discount"].value_counts()

Discount
0.90    14
1.02    13
1.06    13
0.32    12
0.12    11
        ..
0.02     3
0.91     2
0.79     2
0.92     2
0.72     1
Name: count, Length: 126, dtype: int64

In [53]:
# CHECKING GROUP-WISE UNIQUE VALUES

data.groupby(['Gender_Category','Product_Line'])['Discount'].unique()

Gender_Category  Product_Line
Kids             Basketball      [nan, 0.38, 0.86, 1.19, 1.13, 1.24, 1.12, 0.66...
                 Lifestyle       [nan, 0.6, 0.24, 0.86, 0.89, 0.16, 0.95, 0.05,...
                 Running         [nan, 0.84, 0.32, 0.15, 1.01, 0.83, 0.06, 1.04...
                 Soccer          [nan, 0.67, 0.97, 0.81, 0.32, 1.1, 0.53, 0.77,...
                 Training        [0.94, 0.47, nan, 0.32, 0.5, 0.2, 1.19, 0.01, ...
Men              Basketball      [nan, 0.85, 0.22, 0.57, 0.74, 1.06, 0.36, 0.78...
                 Lifestyle       [0.36, nan, 0.12, 1.1, 0.94, 1.14, 0.67, 1.24,...
                 Running         [nan, 0.66, 0.82, 0.21, 0.8, 0.57, 0.29, 0.09,...
                 Soccer          [nan, 0.7, 1.05, 0.82, 0.77, 0.45, 0.24, 0.95,...
                 Training        [nan, 1.17, 0.08, 0.35, 0.12, 1.08, 0.57, 0.69...
Women            Basketball      [0.44, nan, 0.3, 0.37, 0.16, 1.13, 0.48, 0.97,...
                 Lifestyle       [0.24, nan, 0.22, 0.84, 1.06, 1.07, 1.23, 0.78...
                 Running         [nan, 1.02, 0.8, 0.5, 0.85, 0.32, 0.51, 1.1, 0...
                 Soccer          [nan, 0.56, 0.71, 0.96, 0.39, 0.76, 0.77, 0.95...
                 Training        [nan, 1.02, 0.26, 0.63, 0.6, 0.53, 0.41, 1.2, ...
Name: Discount, dtype: object

In [54]:
# CHECKING GROUP-WISE MEDIAN

data.groupby(['Gender_Category','Product_Line'])['Discount'].median()

Gender_Category  Product_Line
Kids             Basketball      0.660
                 Lifestyle       0.605
                 Running         0.670
                 Soccer          0.685
                 Training        0.580
Men              Basketball      0.495
                 Lifestyle       0.730
                 Running         0.555
                 Soccer          0.725
                 Training        0.505
Women            Basketball      0.670
                 Lifestyle       0.750
                 Running         0.615
                 Soccer          0.595
                 Training        0.555
Name: Discount, dtype: float64

In [55]:
# FILLING NULL VALUES WITH THE GROUP-WISE MEDIAN

data['Discount']=data.groupby(['Gender_Category','Product_Line'])['Discount'].transform(lambda x: x.fillna(x[x!=0].median()))

In [56]:
# CHECKING AVG DISCOUNT AS A WHOLE.

data['Discount'].mean()

np.float64(0.629494)

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2500 entries, 211 to 2499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2500 non-null   int64
 1   Gender_Category  2500 non-null   object
 2   Product_Line     2500 non-null   object
 3   Product_Name     2500 non-null   object
 4   Size             2500 non-null   int64
 5   Units_Sold       2500 non-null   int64
 6   MRP              1246 non-null   float64
 7   Discount         2500 non-null   float64
 8   Revenue          2500 non-null   float64
 9   Order_Date       2500 non-null   object
 10  Sales_Channel    2500 non-null   object
 11  Region           2500 non-null   object
 12  Profit           2500 non-null   float64
dtypes: float64(4), int64(3), object(6)
memory usage: 273.4+ KB

-> THE DISCOUNT COLUMN HAD NULL VALUES AND WAS FILLED WITH THE GROUP-WISE MEDIAN, IT WAS COMPARED WHETHER TO USE MEDIAN OR MEAN TO FILL THE VALUES, BUT BECAUSE OF THE DIVERSITY OF THE VALUES AND PRESENCE OF OUTLIERS IT WAS FILLED WITH MEDIAN, WHEN CHECK THE OVERALL AVG. OF THE DISCOUNT AFTER FILLING IT WITH MEDIAN IT WAS AROUND 0.6 I.E. 60%.

-> DURING FUTHER ENQUIRY AND PRE-PROCESSING, IT WAS FOUND THAT THE DISCOUNT COLUMN IN ACTUAL WAS HOLDING THE DISCOUNT PERCENTAGE AND THE ABOUSLUTE DISCOUNTED AMOUNT.

-> FURTHERMORE AFTER DOING COMPUTATION IT WAS FOUND THAT THE DISCOUNT COLUMN IS HOLDING THE PERCENTAGE OF AMOUNT ACTUALLY PAID BY THE CUSTOMER AND NOT THE DISCOUNT PERCENTAGE.

-> THESE THINGS ARE HANDELED LATER ON IN THE SHEET.

### CLEANING AND PRE-PROCESSING THE MRP COLUMN

In [58]:
# CHECKING IMPORTANT MEASURES TO ANALYSE THE DATA DISTRIBUTION ND QUALITY

data['MRP'].describe()

count    1246.000000
mean     6039.863395
std      2315.746826
min      2006.630000
25%      4038.902500
50%      6110.030000
75%      8022.187500
max      9996.220000
Name: MRP, dtype: float64

In [59]:
#CHECKING THE NULL VALUES 

data['MRP'].isnull().sum()

np.int64(1254)

In [60]:
# CHECKING THE DIVERSITY OF THE PRODUCTS CATEGORY W.R.T. MRP (HIGH POSSIBILITY OF OUTLIERS ARE HENCE MEDIAN IS SUGGESTED).

data.groupby(['Gender_Category','Product_Line','Product_Name'])['MRP'].unique()

Gender_Category  Product_Line  Product_Name
Kids             Basketball    Air Jordan            [3285.52, 8918.66, 4251.74, nan, 9520.5, 8267....
                               Kyrie Flytrap         [6436.11, 4280.01, nan, 9023.07, 6708.16, 3134...
                               LeBron 20             [nan, 4934.46, 5357.49, 3588.38, 7806.98, 2222...
                               Zoom Freak            [nan, 4656.28, 8426.54, 7214.55, 9382.15, 8631...
                 Lifestyle     Air Force 1           [7609.9, nan, 6066.5, 3360.35, 7568.04, 4195.0...
                               Blazer Mid            [9673.57, nan, 7126.64, 4032.43, 7849.81, 2963...
                               Dunk Low              [nan, 8165.07, 6202.99, 4834.65, 2278.67, 9541...
                               Waffle One            [7949.83, 4561.67, nan, 5119.41, 5389.56, 3375...
                 Running       Air Zoom              [3424.06, nan, 9246.88, 5321.46, 9307.2, 2221....
                               Free RN               [nan, 2010.07, 5561.82, 4004.36, 2504.09, 4638...
                               Pegasus Turbo         [nan, 9220.15, 3360.35, 5653.14, 4891.02, 5399...
                               React Infinity        [nan, 5395.6, 7557.71, 4128.35, 6437.85, 4110....
                 Soccer        Mercurial Superfly    [9794.84, nan, 8482.43, 6245.23, 5891.32, 5037...
                               Phantom GT            [nan, 9507.54, 5937.52, 7607.45, 8998.44, 4728...
                               Premier III           [2068.95, nan, 2708.73, 9649.28, 7645.41, 5185...
                               Tiempo Legend         [nan, 5553.88, 4414.63, 8290.97, 7767.2, 5619....
                 Training      Flex Trainer          [nan, 4554.97, 4276.36, 4046.05, 9180.15, 2749...
                               Metcon 7              [nan, 6548.87, 5744.7, 5089.88, 6591.41, 3019....
                               SuperRep Go           [nan, 9671.05, 4577.65, 4348.86, 8484.82, 4993...
                               ZoomX Invincible      [nan, 6743.07, 5474.79, 5179.57, 7900.02, 2932...
Men              Basketball    Air Jordan            [nan, 6235.71, 9593.65, 5570.72, 6331.64, 5967...
                               Kyrie Flytrap         [2824.55, 5254.47, nan, 7561.85, 7918.93, 9149...
                               LeBron 20             [nan, 8335.48, 7660.41, 5016.03, 4179.34, 4248...
                               Zoom Freak            [nan, 9106.61, 6765.74, 8031.83, 7154.83, 4468...
                 Lifestyle     Air Force 1           [2452.52, 6009.58, nan, 6903.22, 3059.89, 7408...
                               Blazer Mid            [nan, 3723.21, 8903.17, 7662.11, 9747.58, 3239...
                               Dunk Low              [2174.89, 3598.07, nan, 6537.29, 3718.82, 8293...
                               Waffle One            [6064.42, nan, 5003.95, 5245.87, 6216.29, 7979...
                 Running       Air Zoom              [nan, 5614.96, 7143.23, 8228.88, 5881.13, 5550...
                               Free RN               [8072.86, 7086.7, nan, 2553.29, 9291.74, 6620....
                               Pegasus Turbo         [4322.06, nan, 8055.2, 2904.11, 6310.25, 6243....
                               React Infinity        [2180.71, nan, 3055.79, 7795.32, 2890.77, 3477...
                 Soccer        Mercurial Superfly    [nan, 6196.01, 7330.81, 7982.2, 8062.11, 5308....
                               Phantom GT            [7652.31, 3998.0, nan, 6136.45, 5259.05, 5222....
                               Premier III           [7204.01, 3493.04, 3492.89, nan, 6121.21, 5028...
                               Tiempo Legend         [nan, 2786.84, 2483.97, 7603.38, 6041.3, 4819....
                 Training      Flex Trainer          [3270.23, nan, 9155.96, 6189.1, 7730.77, 9695....
                               Metcon 7              [nan, 4020.5, 6789.53, 8249.96, 9061.25, 6458....
                               SuperRep Go           [6819.78, nan, 5571.14, 2225.73, 2640.04, 4004...
                               ZoomX Invincible      [nan, 5091.2, 5690.69, 4738.62, 8897.19, 5622....
Women            Basketball    Air Jordan            [9871.75, nan, 9751.0, 3939.34, 8141.8, 7634.6...
                               Kyrie Flytrap         [9820.5, nan, 5649.99, 7901.16, 7510.8, 2685.9...
                               LeBron 20             [3272.45, nan, 6970.47, 6777.88, 4038.32, 8750...
                               Zoom Freak            [9041.15, 5075.22, 8799.22, nan, 7507.91, 3036...
                 Lifestyle     Air Force 1           [9378.52, 7312.38, nan, 3111.62, 8637.25, 6453...
                               Blazer Mid            [nan, 7670.82, 3676.04, 2699.59, 8359.07, 9585...
                               Dunk Low              [nan, 6481.4, 9936.94, 4357.79, 3028.41, 3403....
                               Waffle One            [7203.25, 8516.45, nan, 5582.98, 4374.83, 4784...
                 Running       Air Zoom              [2491.06, 5714.92, 3075.72, nan, 6188.29, 2708...
                               Free RN               [nan, 2149.28, 9369.1, 5620.64, 6178.39, 6743....
                               Pegasus Turbo         [nan, 8016.24, 5996.09, 7810.49, 8889.68, 8203...
                               React Infinity        [nan, 7518.66, 8136.39, 9344.52, 9701.72, 2265...
                 Soccer        Mercurial Superfly    [2298.45, nan, 4301.85, 8206.22, 6569.65, 3068...
                               Phantom GT            [nan, 3883.92, 6012.23, 3042.37, 3700.75, 3328...
                               Premier III           [nan, 9804.64, 5172.14, 2422.97, 4254.68, 9145...
                               Tiempo Legend         [4957.93, nan, 9662.04, 3642.21, 3502.97, 8644...
                 Training      Flex Trainer          [7363.96, 9586.08, nan, 2767.7, 4985.92, 6874....
                               Metcon 7              [nan, 2201.54, 4071.46, 9488.84, 4819.76, 8609...
                               SuperRep Go           [8577.75, 7502.24, 7645.96, nan, 2070.97, 3664...
                               ZoomX Invincible      [6820.42, 7850.87, 7338.57, nan, 7978.89, 3987...
Name: MRP, dtype: object

In [61]:
# CHECKING THE DIVERSITY IN MRP WHEN SIZE ALSO INCLUDED (DUE TO PRESENCE OF NULL VALUES, NO MUCH DATA AVAILABLE) 

data.groupby(['Gender_Category','Product_Line','Product_Name','Size'])['MRP'].unique()

Gender_Category  Product_Line  Product_Name      Size
Kids             Basketball    Air Jordan        8                         [9520.5, 3572.52, nan, 3701.59]
                                                 9       [3285.52, 8267.56, nan, 2809.8, 8132.33, 8046....
                                                 10      [4251.74, nan, 9405.77, 6165.08, 9250.25, 9700...
                                                 11                                                  [nan]
                                                 12      [8918.66, nan, 9062.25, 5300.32, 6975.67, 8741...
                                                                               ...
Women            Training      ZoomX Invincible  8       [7988.99, nan, 5923.67, 5045.62, 8292.37, 9213...
                                                 9        [2503.6, nan, 9501.17, 9738.93, 5864.29, 5358.7]
                                                 10                                [nan, 8735.51, 8873.61]
                                                 11                                         [nan, 6424.32]
                                                 12      [6820.42, 7850.87, 7338.57, 7978.89, 3987.65, ...
Name: MRP, Length: 367, dtype: object

In [62]:
# CHECKING THE GROUP-WISE MEAN BASED ON THREE CATEGORIES TO FILL NULL VALUES IN MRP

data.groupby(['Gender_Category','Product_Line','Product_Name'])['MRP'].median()

Gender_Category  Product_Line  Product_Name
Kids             Basketball    Air Jordan            6966.160
                               Kyrie Flytrap         4917.280
                               LeBron 20             6329.600
                               Zoom Freak            6021.235
                 Lifestyle     Air Force 1           6554.310
                               Blazer Mid            6569.370
                               Dunk Low              6122.675
                               Waffle One            5254.485
                 Running       Air Zoom              5837.530
                               Free RN               5691.680
                               Pegasus Turbo         5374.340
                               React Infinity        6070.190
                 Soccer        Mercurial Superfly    6892.095
                               Phantom GT            6466.570
                               Premier III           5275.855
                               Tiempo Legend         5186.225
                 Training      Flex Trainer          6295.000
                               Metcon 7              5817.695
                               SuperRep Go           4912.450
                               ZoomX Invincible      6584.055
Men              Basketball    Air Jordan            5974.920
                               Kyrie Flytrap         5124.650
                               LeBron 20             6730.480
                               Zoom Freak            6172.360
                 Lifestyle     Air Force 1           6009.580
                               Blazer Mid            4936.545
                               Dunk Low              7588.770
                               Waffle One            6147.510
                 Running       Air Zoom              4854.180
                               Free RN               7450.800
                               Pegasus Turbo         6211.380
                               React Infinity        6870.705
                 Soccer        Mercurial Superfly    7150.045
                               Phantom GT            6319.755
                               Premier III           6121.210
                               Tiempo Legend         6041.300
                 Training      Flex Trainer          6252.925
                               Metcon 7              6284.840
                               SuperRep Go           5157.745
                               ZoomX Invincible      7050.140
Women            Basketball    Air Jordan            6144.015
                               Kyrie Flytrap         5912.915
                               LeBron 20             6271.660
                               Zoom Freak            7388.230
                 Lifestyle     Air Force 1           7309.080
                               Blazer Mid            7671.065
                               Dunk Low              4722.755
                               Waffle One            4934.050
                 Running       Air Zoom              5550.990
                               Free RN               5698.690
                               Pegasus Turbo         6047.945
                               React Infinity        7006.295
                 Soccer        Mercurial Superfly    4262.630
                               Phantom GT            6356.455
                               Premier III           5255.980
                               Tiempo Legend         7253.300
                 Training      Flex Trainer          6496.580
                               Metcon 7              5462.800
                               SuperRep Go           5931.250
                               ZoomX Invincible      6882.310
Name: MRP, dtype: float64

In [63]:
# CHECKING THE MEAN TO COMPARE BETWEEN THE FILLING MEASURE 

data.groupby(['Gender_Category','Product_Line','Product_Name'])['MRP'].mean()

Gender_Category  Product_Line  Product_Name
Kids             Basketball    Air Jordan            6515.394348
                               Kyrie Flytrap         5592.425652
                               LeBron 20             6092.702917
                               Zoom Freak            5753.526667
                 Lifestyle     Air Force 1           6111.002778
                               Blazer Mid            6249.062000
                               Dunk Low              5934.514375
                               Waffle One            5824.477000
                 Running       Air Zoom              6287.730476
                               Free RN               5683.752069
                               Pegasus Turbo         5924.175385
                               React Infinity        5994.008889
                 Soccer        Mercurial Superfly    6606.526875
                               Phantom GT            6118.586667
                               Premier III           5476.304286
                               Tiempo Legend         5069.284444
                 Training      Flex Trainer          6271.275833
                               Metcon 7              5868.022727
                               SuperRep Go           5437.170769
                               ZoomX Invincible      6496.040000
Men              Basketball    Air Jordan            5887.565357
                               Kyrie Flytrap         5491.801500
                               LeBron 20             6428.668261
                               Zoom Freak            6159.240526
                 Lifestyle     Air Force 1           6065.977200
                               Blazer Mid            5460.065000
                               Dunk Low              6648.028571
                               Waffle One            5869.640000
                 Running       Air Zoom              4972.478667
                               Free RN               6782.241765
                               Pegasus Turbo         6086.061000
                               React Infinity        6215.576875
                 Soccer        Mercurial Superfly    6751.348889
                               Phantom GT            6300.717188
                               Premier III           5837.721429
                               Tiempo Legend         5403.800909
                 Training      Flex Trainer          5731.269643
                               Metcon 7              6038.343571
                               SuperRep Go           5273.361667
                               ZoomX Invincible      6855.889130
Women            Basketball    Air Jordan            6083.077500
                               Kyrie Flytrap         5662.294286
                               LeBron 20             5959.366452
                               Zoom Freak            6629.322500
                 Lifestyle     Air Force 1           6522.581667
                               Blazer Mid            6415.233889
                               Dunk Low              5658.034091
                               Waffle One            5576.200952
                 Running       Air Zoom              6086.311304
                               Free RN               5764.328333
                               Pegasus Turbo         6043.972857
                               React Infinity        6566.237500
                 Soccer        Mercurial Superfly    5155.215294
                               Phantom GT            6027.539375
                               Premier III           5929.124706
                               Tiempo Legend         6932.811176
                 Training      Flex Trainer          6357.099130
                               Metcon 7              5633.477778
                               SuperRep Go           5966.121786
                               ZoomX Invincible      6571.443846
Name: MRP, dtype: float64

In [64]:
# FILLING THE NULL VALUES WITH GROUP-WISE MEDIAN AFTER COMPARING AND BASED ON THREE CATEGORIES IN GROUP FOR HIGHER ACCURACY.

data['MRP']=data.groupby(['Gender_Category','Product_Line','Product_Name'])['MRP'].transform(lambda x: x.fillna(x[x!=0].median()))

In [65]:
data.isnull().sum()

Order_ID           0
Gender_Category    0
Product_Line       0
Product_Name       0
Size               0
Units_Sold         0
MRP                0
Discount           0
Revenue            0
Order_Date         0
Sales_Channel      0
Region             0
Profit             0
dtype: int64

In [66]:
data

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Discount,Revenue,Order_Date,Sales_Channel,Region,Profit
211,2000,Kids,Training,Metcon 7,9,4,5817.695,0.940,0.0,27-02-2024,Retail,bengaluru,2372.82
0,2000,Kids,Training,SuperRep Go,8,3,4912.450,0.470,0.0,09-03-2024,Online,bengaluru,-770.45
121,2000,Kids,Running,React Infinity,8,1,6070.190,0.670,0.0,20-11-2023,Retail,Kolkata,929.75
1,2001,Women,Soccer,Tiempo Legend,8,3,4957.930,0.595,0.0,09-07-2024,Retail,Hyd,-112.53
1205,2002,Women,Lifestyle,Dunk Low,7,2,4722.755,0.240,0.0,11-12-2024,Online,Delhi,912.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,12,3,4917.280,0.660,0.0,14-05-2025,Online,Pune,2.97
2496,4496,Men,Basketball,Kyrie Flytrap,10,1,5124.650,0.495,0.0,31-12-2024,Online,Hyd,-487.36
2497,4497,Men,Soccer,Tiempo Legend,7,1,6647.600,0.520,0.0,07-02-2025,Retail,Bangalore,-918.14
2498,4498,Women,Training,ZoomX Invincible,9,4,5358.700,0.555,0.0,12-11-2024,Online,Mumbai,3352.29
2499,4499,Women,Running,Air Zoom,8,1,5550.990,0.615,0.0,23-11-2024,Retail,Mumbai,2453.57

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2500 entries, 211 to 2499
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2500 non-null   int64
 1   Gender_Category  2500 non-null   object
 2   Product_Line     2500 non-null   object
 3   Product_Name     2500 non-null   object
 4   Size             2500 non-null   int64
 5   Units_Sold       2500 non-null   int64
 6   MRP              2500 non-null   float64
 7   Discount         2500 non-null   float64
 8   Revenue          2500 non-null   float64
 9   Order_Date       2500 non-null   object
 10  Sales_Channel    2500 non-null   object
 11  Region           2500 non-null   object
 12  Profit           2500 non-null   float64
dtypes: float64(4), int64(3), object(6)
memory usage: 273.4+ KB

-> THE MRP COLUMN HAD NULL VALUES AS ITS ONLY PROBLEM.

-> TO FILL THE NULL VALUES MEDIAN AND MEAN WAS COMPARED, ALTHOUGH FROM THE GROUP-WISE REFLECITION BASED ON THREE COLUMNS AND DECISIVE FACTORS, IT SHOWED THAT THERE ARE OTULIERS IN THE MRP SECTION FOR ALMOST EVERY GROUP, HENCE MEDIAN WAS THE BEST CHOICE.

-> AFTER INCLUDING SIZE BASED INFORMATION, THERE WASNT MUCH EVIDENCE AND CONCRETE INFO SO THAT IT CAN BE USED FOR DECICION MAKING.

### CLEANING AND PRE-PROCESSING THE REVENUE COLUMN

-> REVENUE HAS SOME 0.0 VALUES, BUT FOR THE SAME VALUES I AM HAVING THE PROFIT VALUES, MAKING THE CALCULATION BASED ON THE INFORMATION OF QUANTITY, MRP AND DISCOUNT IT CAME TO NOTICE THAT DISCOUNT IS ACTUALLY HAVING THE PERCENTAGE AND THAT TO THE PERCENTAGE OF THE AMOUNT ACTUALLY PAID BY THE CUSTOMER AND THE DISCOUNT GIVEN TO THE CUSTOMER, HENCE I MADE SOME CHANGES IN THE DATAFRAME ITSELF FOR BETTER INSIGHT AND TO CALCULATE THE ACTUAL ANMD ACCURATE REVENUE.

-> NEW COLUMN "%_pricepaid" EXACTLY SAME VALUES AS IN DISCOUNT.
-> NEW DISCOUNT COLUMN CONTAING THE ACUTALY PERCENTAGE OF DISCOUNT APPLIED ON THE "MRP*UNITS_SOLD".

In [68]:
data['%_pricepaid'] = data['Discount']
data['Discount'] = 1-data['Discount']

In [69]:
# CHANGING TO ABSOLUTE PERCENTAGE VALUE DIRECTLY RATHER THAN FLOAT COMPUTED VALUES

data['Discount%'] = data['Discount']*100

In [70]:
# DELETED THE ERRORNEOUS AND MISSINFORMING DISCOUNT COLUMN.

data.drop('Discount',axis=1,inplace=True)

In [71]:
#CHECKING THE NULL VALUES

data['Revenue'].isnull().sum()

np.int64(0)

In [72]:
# CHECKING FOR ANY VALUES REMAINED

data[data['Revenue']==0]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Revenue,Order_Date,Sales_Channel,Region,Profit,%_pricepaid,Discount%
211,2000,Kids,Training,Metcon 7,9,4,5817.695,0.0,27-02-2024,Retail,bengaluru,2372.82,0.940,6.0
0,2000,Kids,Training,SuperRep Go,8,3,4912.450,0.0,09-03-2024,Online,bengaluru,-770.45,0.470,53.0
121,2000,Kids,Running,React Infinity,8,1,6070.190,0.0,20-11-2023,Retail,Kolkata,929.75,0.670,33.0
1,2001,Women,Soccer,Tiempo Legend,8,3,4957.930,0.0,09-07-2024,Retail,Hyd,-112.53,0.595,40.5
1205,2002,Women,Lifestyle,Dunk Low,7,2,4722.755,0.0,11-12-2024,Online,Delhi,912.61,0.240,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,12,3,4917.280,0.0,14-05-2025,Online,Pune,2.97,0.660,34.0
2496,4496,Men,Basketball,Kyrie Flytrap,10,1,5124.650,0.0,31-12-2024,Online,Hyd,-487.36,0.495,50.5
2497,4497,Men,Soccer,Tiempo Legend,7,1,6647.600,0.0,07-02-2025,Retail,Bangalore,-918.14,0.520,48.0
2498,4498,Women,Training,ZoomX Invincible,9,4,5358.700,0.0,12-11-2024,Online,Mumbai,3352.29,0.555,44.5
2499,4499,Women,Running,Air Zoom,8,1,5550.990,0.0,23-11-2024,Retail,Mumbai,2453.57,0.615,38.5

In [73]:
# CALCULATING THE NEW AND ACTUAL REVENUE BASED ON THE INFORMATION AVAILABLE

data['Revenue'] = data['Units_Sold'] * data['MRP'] * data['%_pricepaid']

-> THE REVENUE COLUMN STILL HAD SOME ROWS, IN THESE ROWS THERE WAS 100 PERCENT DISCOUNT, YET THE PROFIT WAS MENTIONED, HENCE I DECIDED TO DROP THESE COLUMN BUT STORE THEM SEPARTELY IN ANOTHER VARIABLE TO MENTION IT AND KNOW THE ACTUAL CAUSE.

-> IT WAS MUCH HARDER TO IDENTIFY WHAT IS WRONG AND WHAT IS WRONG BECAUSE EVENTUALLY THESE ORDER MIGHT BE GIVEN FREE FOR PROMOTIONAL PURPOSE AND ANYTHING ELSE, HENCE RATHER THEN LETTING THESE ROWS TO AFFECT THE DATA QUALITY IT WAS MUCH BETTER TO MAKE A RECORD OF THEM AND DROP THEM FROM ANALYSIS.

In [74]:
data[data['Revenue']==0]

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Revenue,Order_Date,Sales_Channel,Region,Profit,%_pricepaid,Discount%
2124,4124,Kids,Basketball,LeBron 20,8,1,6329.600,0.0,16-10-2023,Online,Delhi,477.62,0.0,100.0
2207,4207,Women,Basketball,Air Jordan,10,2,6144.015,0.0,15-11-2024,Retail,Hyderabad,2063.27,0.0,100.0
2214,4214,Men,Training,SuperRep Go,9,3,5157.745,0.0,08-11-2024,Retail,Pune,1393.11,0.0,100.0
2362,4362,Men,Training,Flex Trainer,9,3,6252.925,0.0,08-07-2025,Online,Kolkata,-81.22,0.0,100.0

In [75]:
# DROPPING THE ROWS AND AMKING A SEPARATE RECORD OF THE ERRORNEOUS ROWS.

sec_cons = data[data['Revenue']==0]
sec_cons
data.drop([2124,2207,2214,2362],axis=0,inplace=True)

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2496 entries, 211 to 2499
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2496 non-null   int64
 1   Gender_Category  2496 non-null   object
 2   Product_Line     2496 non-null   object
 3   Product_Name     2496 non-null   object
 4   Size             2496 non-null   int64
 5   Units_Sold       2496 non-null   int64
 6   MRP              2496 non-null   float64
 7   Revenue          2496 non-null   float64
 8   Order_Date       2496 non-null   object
 9   Sales_Channel    2496 non-null   object
 10  Region           2496 non-null   object
 11  Profit           2496 non-null   float64
 12  %_pricepaid      2496 non-null   float64
 13  Discount%        2496 non-null   float64
dtypes: float64(5), int64(3), object(6)
memory usage: 292.5+ KB

-> THE REVENUE COLUMN IN REAL IS THE SELLING PRICE OR THE TOTAL AMOUNT RECEVIED FROM THE CUSTOMER FOR THEIR RESPECTIVE ORDER.

-> NEW REVENUE WAS CALCULATED AND REPLACED WITH THE ACTUALY WAY OF COMPUTATION AFTER GETTING DETAILS AND FORMULAS FROM GOOGLE.
    
-> TWO NEW COLUMN WERE CREATED FOR BETTER AND CLEAR UNDERSTANDING DURING THE ANALYSIS.

In [77]:
# ADDING THE COST PRICE COLUMN

data['Cost_Price'] = data['Revenue'] - data['Profit']
data

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Revenue,Order_Date,Sales_Channel,Region,Profit,%_pricepaid,Discount%,Cost_Price
211,2000,Kids,Training,Metcon 7,9,4,5817.695,21874.53320,27-02-2024,Retail,bengaluru,2372.82,0.940,6.0,19501.71320
0,2000,Kids,Training,SuperRep Go,8,3,4912.450,6926.55450,09-03-2024,Online,bengaluru,-770.45,0.470,53.0,7697.00450
121,2000,Kids,Running,React Infinity,8,1,6070.190,4067.02730,20-11-2023,Retail,Kolkata,929.75,0.670,33.0,3137.27730
1,2001,Women,Soccer,Tiempo Legend,8,3,4957.930,8849.90505,09-07-2024,Retail,Hyd,-112.53,0.595,40.5,8962.43505
1205,2002,Women,Lifestyle,Dunk Low,7,2,4722.755,2266.92240,11-12-2024,Online,Delhi,912.61,0.240,76.0,1354.31240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,12,3,4917.280,9736.21440,14-05-2025,Online,Pune,2.97,0.660,34.0,9733.24440
2496,4496,Men,Basketball,Kyrie Flytrap,10,1,5124.650,2536.70175,31-12-2024,Online,Hyd,-487.36,0.495,50.5,3024.06175
2497,4497,Men,Soccer,Tiempo Legend,7,1,6647.600,3456.75200,07-02-2025,Retail,Bangalore,-918.14,0.520,48.0,4374.89200
2498,4498,Women,Training,ZoomX Invincible,9,4,5358.700,11896.31400,12-11-2024,Online,Mumbai,3352.29,0.555,44.5,8544.02400
2499,4499,Women,Running,Air Zoom,8,1,5550.990,3413.85885,23-11-2024,Retail,Mumbai,2453.57,0.615,38.5,960.28885

In [78]:
# ADDING PROFIT/LOSS% COLUMN

data['Profit/Loss_%'] = (data['Profit']/data['Cost_Price']) * 100
data

,Order_ID,Gender_Category,Product_Line,Product_Name,Size,Units_Sold,MRP,Revenue,Order_Date,Sales_Channel,Region,Profit,%_pricepaid,Discount%,Cost_Price,Profit/Loss_%
211,2000,Kids,Training,Metcon 7,9,4,5817.695,21874.53320,27-02-2024,Retail,bengaluru,2372.82,0.940,6.0,19501.71320,12.167239
0,2000,Kids,Training,SuperRep Go,8,3,4912.450,6926.55450,09-03-2024,Online,bengaluru,-770.45,0.470,53.0,7697.00450,-10.009738
121,2000,Kids,Running,React Infinity,8,1,6070.190,4067.02730,20-11-2023,Retail,Kolkata,929.75,0.670,33.0,3137.27730,29.635570
1,2001,Women,Soccer,Tiempo Legend,8,3,4957.930,8849.90505,09-07-2024,Retail,Hyd,-112.53,0.595,40.5,8962.43505,-1.255574
1205,2002,Women,Lifestyle,Dunk Low,7,2,4722.755,2266.92240,11-12-2024,Online,Delhi,912.61,0.240,76.0,1354.31240,67.385487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,4495,Kids,Basketball,Kyrie Flytrap,12,3,4917.280,9736.21440,14-05-2025,Online,Pune,2.97,0.660,34.0,9733.24440,0.030514
2496,4496,Men,Basketball,Kyrie Flytrap,10,1,5124.650,2536.70175,31-12-2024,Online,Hyd,-487.36,0.495,50.5,3024.06175,-16.116073
2497,4497,Men,Soccer,Tiempo Legend,7,1,6647.600,3456.75200,07-02-2025,Retail,Bangalore,-918.14,0.520,48.0,4374.89200,-20.986575
2498,4498,Women,Training,ZoomX Invincible,9,4,5358.700,11896.31400,12-11-2024,Online,Mumbai,3352.29,0.555,44.5,8544.02400,39.235494
2499,4499,Women,Running,Air Zoom,8,1,5550.990,3413.85885,23-11-2024,Retail,Mumbai,2453.57,0.615,38.5,960.28885,255.503331

-> ADDED TWO COLUMN i.e. "Cost_Price" & "Profit/Loss_%" FOR MORE CLEAR AND NEW INSIGHTS ABOUT THE SALES.

In [79]:
data.to_csv("NIKE_SALES_CLEANED.csv")

### CLEANING AND PRE-PROCESSING REGION COLUMN

In [84]:
data['Region'].value_counts()

Region
Delhi        437
Bangalore    436
Mumbai       418
Kolkata      416
Hyderabad    402
Pune         387
Name: count, dtype: int64

In [ ]:
# CORRECTING THE ERRONEOUS ENTRIES IN THE REGION COLUMN TO MAKE IT MORE INFORMATIVE AND ACCURATE.

data['Region'].replace('Hyd','Hyderabad',inplace=True)
data['Region'].replace('hyderbad','Hyderabad',inplace=True)
data['Region'].replace('bengaluru','Bangalore',inplace=True)

In [ ]:
an_data = data.copy()

<class 'pandas.core.frame.DataFrame'>
Index: 2496 entries, 211 to 2499
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2496 non-null   int64
 1   Gender_Category  2496 non-null   object
 2   Product_Line     2496 non-null   object
 3   Product_Name     2496 non-null   object
 4   Size             2496 non-null   int64
 5   Units_Sold       2496 non-null   int64
 6   MRP              2496 non-null   float64
 7   Revenue          2496 non-null   float64
 8   Order_Date       2496 non-null   object
 9   Sales_Channel    2496 non-null   object
 10  Region           2496 non-null   object
 11  Profit           2496 non-null   float64
 12  %_pricepaid      2496 non-null   float64
 13  Discount%        2496 non-null   float64
 14  Cost_Price       2496 non-null   float64
 15  Profit/Loss_%    2496 non-null   float64
dtypes: float64(7), int64(3), object(6)
memory usage: 331.5+ KB

In [ ]:
# CHANGING THE DATA TYPE IN THE COPIED DATAFRAME TO DATETIME FORMAT TO USE THE FEATURES ASSOCIATED WITH IT.

an_data['Order_Date'] = pd.to_datetime(an_data['Order_Date'],errors='coerce',format='%d-%m-%Y')
an_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2496 entries, 211 to 2499
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         2496 non-null   int64
 1   Gender_Category  2496 non-null   object
 2   Product_Line     2496 non-null   object
 3   Product_Name     2496 non-null   object
 4   Size             2496 non-null   int64
 5   Units_Sold       2496 non-null   int64
 6   MRP              2496 non-null   float64
 7   Revenue          2496 non-null   float64
 8   Order_Date       2496 non-null   datetime64[ns]
 9   Sales_Channel    2496 non-null   object
 10  Region           2496 non-null   object
 11  Profit           2496 non-null   float64
 12  %_pricepaid      2496 non-null   float64
 13  Discount%        2496 non-null   float64
 14  Cost_Price       2496 non-null   float64
 15  Profit/Loss_%    2496 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(3), object(5)
memory usage: 331.5+ KB

In [ ]:
# EXTRACTING THE YEAR, MONTH AND QUARTER FROM THE ORDER_DATE COLUMN TO USE IT FOR ANALYSIS.

an_data['Year'] = an_data['Order_Date'].dt.year
an_data['Month'] = an_data['Order_Date'].dt.month
an_data['Quarter'] = an_data['Order_Date'].dt.quarter

In [96]:
an_data.to_csv("NIKE_SALES_PREPROCESSED.csv", index=False)